### ISSUE TITLE
Throwing `TypeError: [object Object] is not iterable`

### ISSUE THREAD

**Issue by victorlearned** [Sullux/fp-light#30]
Looks this starts to hit on anything after `1.2.3` spreading into a  `compilable` function hits this error. I see this when used within the fp `reduce` and `map` as well. 

Example of failing trivial test:

```javascript
    test('should spread compiled function with an identity param that is spread BROKEN', async () => {
      const inc = compilable(pipe(
        _.foo,
        foo => ({ inc: foo + 1}),
      ));
      const input = { foo: (41) }
      const fn = pipe(
         { ...inc({..._}) }
      )
      expect(await fn(input)).toEqual({ inc: 42 })
    })
 ```
 
 If I simply do a resolve beforehand it works
 
 ```javascript
     test('should spread compiled function with an identity param that is spread', async () => {
      const inc = compilable(pipe(
        _.foo,
        foo => ({ inc: foo + 1}),
      ));
      const input = { foo: (41) }
      const fn = pipe(
        {..._},
        { ...inc(_)},
      )
      expect(await fn(input)).toEqual({ inc: 42 })
    })
  ```
  
  
  Here's an actual error in code that was working on fp `1.2.3`
  
 ```javascript
      TypeError: [object Object] is not iterable
        from 29:__FP_LIGHT_PROPERTY_FUNCTION__ targetPropertyIfExists()<STEP_9> (/home/vlearned/blackbox-sdk/src/blobs/blobs.integration.js:68:27)
```
        
  ```javascript
  // { key?, body, options?, blobOptions? } | Buffer
  // options: {<any s3 object options, options passed directly to s3>}
  // blobOptions: {tags?, permissions?}
  const addBlobFromStream = compilable(pipe(
    assertValid(anyOf(
      isStream,
      { ...hasKeyAndOptions, stream: isStream },
    )),
    when(
      _.stream,
      { ...keyAndOptions, stream: _.stream },
      { key: uuid, stream: _ },
    ),
    uploadBlob,
  ));

   
  // { key?, file, options?, blobOptions? } | String
  // options: {<any s3 object options, options passed directly to s3>}
  // blobOptions: {tags?, permissions?}
  const addBlobFromFile = compilable(pipe(
    assertValid(anyOf(
      isString,
      { ...hasKeyAndOptions, file: isString },
    )),
    when(
      _.file,
      { ...keyAndOptions, file: _.file },
      { key: uuid, file: _ },
    ),
    addBlobFromStream({ ..._, stream: fileStream(_.file), file: $(undefined) }), // THROWS HERE
  ));

  ```
  
  Another now broken example that worked in fp `1.2.17`
  ```javascript
  const batchEntries = reduce({
      state: [],
      reducer: [
        ..._.state,
        { ...pipe(_.value, messageParams), Id: pipe(_.i, String) },
      ],
    });
  ```
  
  But changing to this works:
  ```javascript
 
  const batchEntries = reduce({
      state: [],
      reducer: [
        ..._.state,
        pipe({ ...pipe(_.value, messageParams), Id: pipe(_.i, String) }),
      ],
    });
    
  ``` 
  
  Example with `resolve` not spreading that no longer works
  
  
  ```javascript
  
  const logger = () => {
  const mockLog = jest.fn();
  mockLog.write = (...args) => (v) => mockLog(...resolve(args)(v)) || v;
  return mockLog;
};

      at iterableToArray (node_modules/@sullux/fp-light/index.js:724:13)
      at getSpreadValues (node_modules/@sullux/fp-light/index.js:740:28)
      at node_modules/@sullux/fp-light/index.js:746:15
          at Array.reduce (<anonymous>)
      at node_modules/@sullux/fp-light/index.js:736:26
      at Object.apply (node_modules/@sullux/fp-light/index.js:789:13)
      at src/utils/testUtils.js:17:50
      at Object.apply (node_modules/@sullux/fp-light/index.js:789:13)
      at node_modules/@sullux/fp-light/index.js:1980:15
          at Array.reduce (<anonymous>)
      at handler (node_modules/@sullux/fp-light/index.js:1976:23)
```

**Comment by Sullux** [comment]
Ooo, good one. From what I can see this is not a problem spreading a compilable but a problem spreading a pipe. When you put compilable on a pipe it sees that the pipe is already compilable and skips some of the setup. Problem is that the pipe itself does not fully implement compilable because of various technical reasons, so we end up with something that has half the functionality of a regular compilable.

I _think_ I can fix this one fairly quickly. I'll dig in and confirm some things and see if I can get a fix this morning...

**Comment by victorlearned** [comment]
Cool. I investigated it pretty thoroughly across many projects to try and show all the variations. Kind of a pain :(

**Comment by Sullux** [comment]
I was wrong about this one too. The problem was that there was a bug in the innermost spread logic in the spreadable proxy, the identity proxy and the compilable proxy. I fixed it in all three places and now all the test cases are happy.

See [the PR](https://github.com/Sullux/fp-light/pull/33) for details. Install v 1.2.32 to get this fix.

**Comment by victorlearned** [comment]
Looks good so far! Closing.
