### ISSUE TITLE
`TypeError: Cannot create proxy with a non-object as target or handler` When invoking filter withidentity value to filter `null`

### ISSUE THREAD

**Issue by victorlearned** [Sullux/fp-light#31]
The following use to work on fp `1.2.3` . Seems to work with `undefined`

```javascript
  it('should filter out null', async () => {
    const input = [null, 43, 44]
    const result = pipe(filter(_))
    expect(result(input)).toEqual([43,44])
  })
```

Now throws with

```javascript
  TypeError: Cannot create proxy with a non-object as target or handler
       at fromBase (file:///home/vlearned/fp-light/lib/resolve.js:200:12)
       at filterSync (file:///home/vlearned/fp-light/lib/map.js:156:23)
       at Array.filter (file:///home/vlearned/fp-light/lib/map.js:169:7)
       at Object.apply (file:///home/vlearned/fp-light/lib/resolve.js:462:15)
       at Object.apply (file:///home/vlearned/fp-light/lib/resolve.js:348:11)
       at file:///home/vlearned/fp-light/lib/pipe.js:30:13
       at Array.reduce (<anonymous>)
       at file:///home/vlearned/fp-light/lib/pipe.js:26:21
       at file:///home/vlearned/fp-light/lib/map.test.js:153:12
       at file:///home/vlearned/fp-light/scripts/.testRun_instance.js:119:17
 ```
 
 Easily swap with vanilla js but still it use to work :(

**Comment by Sullux** [comment]
Fixed in v 1.2.33.
